In [ ]:
!pip install python-Levenshtein

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting python-Levenshtein
  Downloading python_Levenshtein-0.20.8-py3-none-any.whl (9.4 kB)
Collecting Levenshtein==0.20.8
  Downloading Levenshtein-0.20.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (174 kB)
     |████████████████████████████████| 174 kB 4.3 MB/s
Collecting rapidfuzz<3.0.0,>=2.3.0
  Downloading rapidfuzz-2.13.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 37.0 MB/s
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.20.8 python-Levenshtein-0.20.8 rapidfuzz-2.13.3

In [ ]:
import nltk
import collections
from difflib import SequenceMatcher
import Levenshtein as levenshtein
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:

# Program to measure the similarity between
# two sentences using cosine similarity.
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def cosine_alg(s1, s2):
  X = s1
  Y = s2

  # tokenization
  X_list = word_tokenize(X)
  Y_list = word_tokenize(Y)

  # sw contains the list of stopwords
  sw = stopwords.words('english')
  l1 =[];l2 =[]

  # remove stop words from the string
  X_set = {w for w in X_list if not w in sw}
  Y_set = {w for w in Y_list if not w in sw}

  # form a set containing keywords of both strings
  rvector = X_set.union(Y_set)
  for w in rvector:
      if w in X_set: l1.append(1) # create a vector
      else: l1.append(0)
      if w in Y_set: l2.append(1)
      else: l2.append(0)
  c = 0

  # cosine formula
  for i in range(len(rvector)):
          c+= l1[i]*l2[i]
  cosine = c / float((sum(l1)*sum(l2))**0.5)
  #print(f"X_set: {X_set}")
  #print(f"Y_set: {Y_set}")
  #print(f"rvector: {rvector}")
  #print(f"l1: {l1}")
  #print(f"l2: {l2}")
  #print(f"similarity: {cosine}")
  return cosine

In [ ]:
# Python3 implementation of above approach
from math import floor

# Function to calculate the
# Jaro Similarity of two strings
def jaro_distance(s1, s2) :

    # If the strings are equal
    if (s1 == s2) :
        return 1.0;

    # Length of two strings
    len1 = len(s1);
    len2 = len(s2);

    if (len1 == 0 or len2 == 0) :
        return 0.0;

    # Maximum distance upto which matching
    # is allowed
    max_dist = (max(len(s1), len(s2)) // 2 ) - 1;

    # Count of matches
    match = 0;

    # Hash for matches
    hash_s1 = [0] * len(s1) ;
    hash_s2 = [0] * len(s2) ;

    # Traverse through the first string
    for i in range(len1) :

        # Check if there is any matches
        for j in range( max(0, i - max_dist),
                    min(len2, i + max_dist + 1)) :

            # If there is a match
            if (s1[i] == s2[j] and hash_s2[j] == 0) :
                hash_s1[i] = 1;
                hash_s2[j] = 1;
                match += 1;
                break;

    # If there is no match
    if (match == 0) :
        return 0.0;

    # Number of transpositions
    t = 0;

    point = 0;

    # Count number of occurrences
    # where two characters match but
    # there is a third matched character
    # in between the indices
    for i in range(len1) :
        if (hash_s1[i]) :

            # Find the next matched character
            # in second string
            while (hash_s2[point] == 0) :
                point += 1;

            if (s1[i] != s2[point]) :
                point += 1;
                t += 1;
            else :
                point += 1;

        t /= 2;

    # Return the Jaro Similarity
    return ((match / len1 + match / len2 +
            (match - t) / match ) / 3.0);

# Jaro Winkler Similarity
def jaro_Winkler(s1, s2) :

    jaro_dist = jaro_distance(s1, s2);

    # If the jaro Similarity is above a threshold
    if (jaro_dist > 0.7) :

        # Find the length of common prefix
        prefix = 0;

        for i in range(min(len(s1), len(s2))) :

            # If the characters match
            if (s1[i] == s2[i]) :
                prefix += 1;

            # Else break
            else :
                break;

        # Maximum of 4 characters are allowed in prefix
        prefix = min(4, prefix);

        # Calculate jaro winkler Similarity
        jaro_dist += 0.1 * prefix * (1 - jaro_dist);

    return jaro_dist;

    s1 = "TRATE"; s2 = "TRACE";

    # Print Jaro-Winkler Similarity of two strings
    print("Jaro-Winkler Similarity =", jaro_Winkler(s1, s2)) ;

In [ ]:
def jaccard_similarity(doc1, doc2):

    # List the unique words in a document
    words_doc1 = set(doc1.split())
    words_doc2 = set(doc2.split())

    # Find the intersection of words list of doc1 & doc2
    intersection = words_doc1.intersection(words_doc2)

    # Find the union of words list of doc1 & doc2
    union = words_doc1.union(words_doc2)

    # Calculate Jaccard similarity score
    # using length of intersection set divided by length of union set
    return float(len(intersection)) / len(union)

In [ ]:
# Dqr Implementation in Python
def ratcliff_obershelp_quick_ratio(s1: str, s2: str) -> float:
    """Return an upper bound on ratio() relatively quickly."""
    length = len(s1) + len(s2)

    if not length:
        return 1.0

    intersect = collections.Counter(s1) & collections.Counter(s2)
    matches = sum(intersect.values())
    return 2.0 * matches / length

In [ ]:
import pandas as pd

In [ ]:
# String Matching Algorithms - Comparison
correct_name = 'Pedro Henrique Salmeron'
correct_name_lower = correct_name.lower()
names = ['Pedro Henrique Salmeron', 'Henrique', 'Pedro Henrique', 'Pedro H.', 'P. Henrique', 'Padre Henrique Salmeron', 'Pastor Henqieu Salmeron', 'pastor henqieu salmeron', 'Pedro Henrique Salame', 'Pedro Henrique Salomãe', 'Pato Henrique Salomãe', 'Pedro Henrique Salomão', 'Pequeno Henrique S.', 'P. H. S.', 'P. H.', 'P. H. Salmeron', 'Pedro Henrique Salmero', 'Pedro', 'Salmeron', 'Panela Salmeron Henrique', 'Pietro H. Salmeron', 'Bianca Salmeron', 'Pedro H. Salmero', 'P. Henriqu Salmero', 'Pedro Henrique Salmerom', 'Pedra Salmora Rocha', 'Petrus Henriques Salmerons', 'Patro Henry Saleron']

baseline = 0.95
name_index = f'Name ({correct_name}) - Baseline: {baseline}'
data = {name_index:[], "Cosine":[], "Jaccard":[], "Jaro":[], "Jaro-Winkler":[], "Ratcliff/Obershelp":[], "Ratcliff/Obershelp (Quick Ratio)":[], "Levenshtein":[]}

for n in names:
  name_lower = n.lower()
  data[name_index].append(n)
  data["Cosine"].append(cosine_alg(correct_name_lower, name_lower))
  data["Jaccard"].append(jaccard_similarity(correct_name_lower, name_lower))
  data["Jaro"].append(jaro_distance(correct_name_lower, name_lower))
  data["Jaro-Winkler"].append(jaro_Winkler(correct_name_lower, name_lower))
  data["Ratcliff/Obershelp"].append(SequenceMatcher(None, correct_name_lower, name_lower).ratio())
  data["Ratcliff/Obershelp (Quick Ratio)"].append(SequenceMatcher(None, correct_name_lower, name_lower).quick_ratio())
  data["Levenshtein"].append(levenshtein.ratio(correct_name_lower, name_lower))

pd.set_option('display.colheader_justify', 'center')

df = pd.DataFrame.from_dict(data)
#df[['Cosine','Jaccard','Jaro','Jaro-Winkler','Ratcliff/Obershelp', "Ratcliff/Obershelp (Quick Ratio)", "Levenshtein"]].style.highlight_between(left=baseline, right=1.0, props='color: lightgreen; font-weight:bold;', axis=0).set_table_styles([dict(selector='th', props=[('text-align', 'start'), ('justify-content', 'center')])]).set_properties(**{'text-align': 'center'})
df.set_index(name_index).style.highlight_between(left=baseline, right=1.0, props='color: lightgreen; font-weight:bold;', axis=0).set_properties(**{'text-align': 'center', 'justify-content': 'center', 'align-content': 'center'})